language: node_js
node_js:
  - "4"
  - "5"
  - "6"

branches:
  only:
  - master

 deploy:
   api_key: "9a76b8c8-bd5f-48fc-96e9-9510f8939007"
   email: fabio.rogerio.sj@gmail.com
   provider: npm

notifications:
  email: false

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - npm install -g cordova
  - npm install

script:
  - npm test
